@Repository
public interface SaveAddressDetailsPolicyLevelDetailsChangeControllerRepository {
    PolicyDtlsResponseDto saveAddressDetails(PolicyAddressOldDto mphAddressNewDto) throws IllegalArgumentException;
}